/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SearchRouteImport } from "./routes/search";
import { Route as CharacterRouteImport } from "./routes/character";
import { Route as PageWithLayoutRouteRouteImport } from "./routes/page-with-layout/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as PageWithoutLayoutIndexRouteImport } from "./routes/page-without-layout/index";
import { Route as CharacterIdRouteImport } from "./routes/character.$id";
import { Route as PageWithoutLayoutIdIndexRouteImport } from "./routes/page-without-layout/$id/index";
import { Route as PageWithLayoutIdIndexRouteImport } from "./routes/page-with-layout/$id/index";
import { Route as CharacterIdEpisodeRouteImport } from "./routes/character.$id.$episode";

const SearchRoute = SearchRouteImport.update({
	id: "/search",
	path: "/search",
	getParentRoute: () => rootRouteImport,
} as any);
const CharacterRoute = CharacterRouteImport.update({
	id: "/character",
	path: "/character",
	getParentRoute: () => rootRouteImport,
} as any);
const PageWithLayoutRouteRoute = PageWithLayoutRouteRouteImport.update({
	id: "/page-with-layout",
	path: "/page-with-layout",
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);
const PageWithoutLayoutIndexRoute = PageWithoutLayoutIndexRouteImport.update({
	id: "/page-without-layout/",
	path: "/page-without-layout/",
	getParentRoute: () => rootRouteImport,
} as any);
const CharacterIdRoute = CharacterIdRouteImport.update({
	id: "/$id",
	path: "/$id",
	getParentRoute: () => CharacterRoute,
} as any);
const PageWithoutLayoutIdIndexRoute =
	PageWithoutLayoutIdIndexRouteImport.update({
		id: "/page-without-layout/$id/",
		path: "/page-without-layout/$id/",
		getParentRoute: () => rootRouteImport,
	} as any);
const PageWithLayoutIdIndexRoute = PageWithLayoutIdIndexRouteImport.update({
	id: "/$id/",
	path: "/$id/",
	getParentRoute: () => PageWithLayoutRouteRoute,
} as any);
const CharacterIdEpisodeRoute = CharacterIdEpisodeRouteImport.update({
	id: "/$episode",
	path: "/$episode",
	getParentRoute: () => CharacterIdRoute,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/page-with-layout": typeof PageWithLayoutRouteRouteWithChildren;
	"/character": typeof CharacterRouteWithChildren;
	"/search": typeof SearchRoute;
	"/character/$id": typeof CharacterIdRouteWithChildren;
	"/page-without-layout": typeof PageWithoutLayoutIndexRoute;
	"/character/$id/$episode": typeof CharacterIdEpisodeRoute;
	"/page-with-layout/$id": typeof PageWithLayoutIdIndexRoute;
	"/page-without-layout/$id": typeof PageWithoutLayoutIdIndexRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/page-with-layout": typeof PageWithLayoutRouteRouteWithChildren;
	"/character": typeof CharacterRouteWithChildren;
	"/search": typeof SearchRoute;
	"/character/$id": typeof CharacterIdRouteWithChildren;
	"/page-without-layout": typeof PageWithoutLayoutIndexRoute;
	"/character/$id/$episode": typeof CharacterIdEpisodeRoute;
	"/page-with-layout/$id": typeof PageWithLayoutIdIndexRoute;
	"/page-without-layout/$id": typeof PageWithoutLayoutIdIndexRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/page-with-layout": typeof PageWithLayoutRouteRouteWithChildren;
	"/character": typeof CharacterRouteWithChildren;
	"/search": typeof SearchRoute;
	"/character/$id": typeof CharacterIdRouteWithChildren;
	"/page-without-layout/": typeof PageWithoutLayoutIndexRoute;
	"/character/$id/$episode": typeof CharacterIdEpisodeRoute;
	"/page-with-layout/$id/": typeof PageWithLayoutIdIndexRoute;
	"/page-without-layout/$id/": typeof PageWithoutLayoutIdIndexRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| "/"
		| "/page-with-layout"
		| "/character"
		| "/search"
		| "/character/$id"
		| "/page-without-layout"
		| "/character/$id/$episode"
		| "/page-with-layout/$id"
		| "/page-without-layout/$id";
	fileRoutesByTo: FileRoutesByTo;
	to:
		| "/"
		| "/page-with-layout"
		| "/character"
		| "/search"
		| "/character/$id"
		| "/page-without-layout"
		| "/character/$id/$episode"
		| "/page-with-layout/$id"
		| "/page-without-layout/$id";
	id:
		| "__root__"
		| "/"
		| "/page-with-layout"
		| "/character"
		| "/search"
		| "/character/$id"
		| "/page-without-layout/"
		| "/character/$id/$episode"
		| "/page-with-layout/$id/"
		| "/page-without-layout/$id/";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	PageWithLayoutRouteRoute: typeof PageWithLayoutRouteRouteWithChildren;
	CharacterRoute: typeof CharacterRouteWithChildren;
	SearchRoute: typeof SearchRoute;
	PageWithoutLayoutIndexRoute: typeof PageWithoutLayoutIndexRoute;
	PageWithoutLayoutIdIndexRoute: typeof PageWithoutLayoutIdIndexRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/search": {
			id: "/search";
			path: "/search";
			fullPath: "/search";
			preLoaderRoute: typeof SearchRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/character": {
			id: "/character";
			path: "/character";
			fullPath: "/character";
			preLoaderRoute: typeof CharacterRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/page-with-layout": {
			id: "/page-with-layout";
			path: "/page-with-layout";
			fullPath: "/page-with-layout";
			preLoaderRoute: typeof PageWithLayoutRouteRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/page-without-layout/": {
			id: "/page-without-layout/";
			path: "/page-without-layout";
			fullPath: "/page-without-layout";
			preLoaderRoute: typeof PageWithoutLayoutIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/character/$id": {
			id: "/character/$id";
			path: "/$id";
			fullPath: "/character/$id";
			preLoaderRoute: typeof CharacterIdRouteImport;
			parentRoute: typeof CharacterRoute;
		};
		"/page-without-layout/$id/": {
			id: "/page-without-layout/$id/";
			path: "/page-without-layout/$id";
			fullPath: "/page-without-layout/$id";
			preLoaderRoute: typeof PageWithoutLayoutIdIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/page-with-layout/$id/": {
			id: "/page-with-layout/$id/";
			path: "/$id";
			fullPath: "/page-with-layout/$id";
			preLoaderRoute: typeof PageWithLayoutIdIndexRouteImport;
			parentRoute: typeof PageWithLayoutRouteRoute;
		};
		"/character/$id/$episode": {
			id: "/character/$id/$episode";
			path: "/$episode";
			fullPath: "/character/$id/$episode";
			preLoaderRoute: typeof CharacterIdEpisodeRouteImport;
			parentRoute: typeof CharacterIdRoute;
		};
	}
}

interface PageWithLayoutRouteRouteChildren {
	PageWithLayoutIdIndexRoute: typeof PageWithLayoutIdIndexRoute;
}

const PageWithLayoutRouteRouteChildren: PageWithLayoutRouteRouteChildren = {
	PageWithLayoutIdIndexRoute: PageWithLayoutIdIndexRoute,
};

const PageWithLayoutRouteRouteWithChildren =
	PageWithLayoutRouteRoute._addFileChildren(PageWithLayoutRouteRouteChildren);

interface CharacterIdRouteChildren {
	CharacterIdEpisodeRoute: typeof CharacterIdEpisodeRoute;
}

const CharacterIdRouteChildren: CharacterIdRouteChildren = {
	CharacterIdEpisodeRoute: CharacterIdEpisodeRoute,
};

const CharacterIdRouteWithChildren = CharacterIdRoute._addFileChildren(
	CharacterIdRouteChildren,
);

interface CharacterRouteChildren {
	CharacterIdRoute: typeof CharacterIdRouteWithChildren;
}

const CharacterRouteChildren: CharacterRouteChildren = {
	CharacterIdRoute: CharacterIdRouteWithChildren,
};

const CharacterRouteWithChildren = CharacterRoute._addFileChildren(
	CharacterRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	PageWithLayoutRouteRoute: PageWithLayoutRouteRouteWithChildren,
	CharacterRoute: CharacterRouteWithChildren,
	SearchRoute: SearchRoute,
	PageWithoutLayoutIndexRoute: PageWithoutLayoutIndexRoute,
	PageWithoutLayoutIdIndexRoute: PageWithoutLayoutIdIndexRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();
