/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CharacterRouteImport } from './routes/character'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactUsCountryRouteImport } from './routes/contact-us.$country'
import { Route as CharacterIdRouteImport } from './routes/character.$id'
import { Route as CharacterIdEpisodeRouteImport } from './routes/character.$id.$episode'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterRoute = CharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsCountryRoute = ContactUsCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => ContactUsRoute,
} as any)
const CharacterIdRoute = CharacterIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CharacterRoute,
} as any)
const CharacterIdEpisodeRoute = CharacterIdEpisodeRouteImport.update({
  id: '/$episode',
  path: '/$episode',
  getParentRoute: () => CharacterIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/character': typeof CharacterRouteWithChildren
  '/contact-us': typeof ContactUsRouteWithChildren
  '/search': typeof SearchRoute
  '/character/$id': typeof CharacterIdRouteWithChildren
  '/contact-us/$country': typeof ContactUsCountryRoute
  '/character/$id/$episode': typeof CharacterIdEpisodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/character': typeof CharacterRouteWithChildren
  '/contact-us': typeof ContactUsRouteWithChildren
  '/search': typeof SearchRoute
  '/character/$id': typeof CharacterIdRouteWithChildren
  '/contact-us/$country': typeof ContactUsCountryRoute
  '/character/$id/$episode': typeof CharacterIdEpisodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/character': typeof CharacterRouteWithChildren
  '/contact-us': typeof ContactUsRouteWithChildren
  '/search': typeof SearchRoute
  '/character/$id': typeof CharacterIdRouteWithChildren
  '/contact-us/$country': typeof ContactUsCountryRoute
  '/character/$id/$episode': typeof CharacterIdEpisodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/character'
    | '/contact-us'
    | '/search'
    | '/character/$id'
    | '/contact-us/$country'
    | '/character/$id/$episode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/character'
    | '/contact-us'
    | '/search'
    | '/character/$id'
    | '/contact-us/$country'
    | '/character/$id/$episode'
  id:
    | '__root__'
    | '/'
    | '/character'
    | '/contact-us'
    | '/search'
    | '/character/$id'
    | '/contact-us/$country'
    | '/character/$id/$episode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharacterRoute: typeof CharacterRouteWithChildren
  ContactUsRoute: typeof ContactUsRouteWithChildren
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character': {
      id: '/character'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof CharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us/$country': {
      id: '/contact-us/$country'
      path: '/$country'
      fullPath: '/contact-us/$country'
      preLoaderRoute: typeof ContactUsCountryRouteImport
      parentRoute: typeof ContactUsRoute
    }
    '/character/$id': {
      id: '/character/$id'
      path: '/$id'
      fullPath: '/character/$id'
      preLoaderRoute: typeof CharacterIdRouteImport
      parentRoute: typeof CharacterRoute
    }
    '/character/$id/$episode': {
      id: '/character/$id/$episode'
      path: '/$episode'
      fullPath: '/character/$id/$episode'
      preLoaderRoute: typeof CharacterIdEpisodeRouteImport
      parentRoute: typeof CharacterIdRoute
    }
  }
}

interface CharacterIdRouteChildren {
  CharacterIdEpisodeRoute: typeof CharacterIdEpisodeRoute
}

const CharacterIdRouteChildren: CharacterIdRouteChildren = {
  CharacterIdEpisodeRoute: CharacterIdEpisodeRoute,
}

const CharacterIdRouteWithChildren = CharacterIdRoute._addFileChildren(
  CharacterIdRouteChildren,
)

interface CharacterRouteChildren {
  CharacterIdRoute: typeof CharacterIdRouteWithChildren
}

const CharacterRouteChildren: CharacterRouteChildren = {
  CharacterIdRoute: CharacterIdRouteWithChildren,
}

const CharacterRouteWithChildren = CharacterRoute._addFileChildren(
  CharacterRouteChildren,
)

interface ContactUsRouteChildren {
  ContactUsCountryRoute: typeof ContactUsCountryRoute
}

const ContactUsRouteChildren: ContactUsRouteChildren = {
  ContactUsCountryRoute: ContactUsCountryRoute,
}

const ContactUsRouteWithChildren = ContactUsRoute._addFileChildren(
  ContactUsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharacterRoute: CharacterRouteWithChildren,
  ContactUsRoute: ContactUsRouteWithChildren,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
